#!/usr/bin/env bash

# set -e

if [ "${#}" -eq 1 ] && [[ "${1}" != "-"* ]]
then
    RESULT=$("${TELEPORT_DIR}/tp_cli" "${@}")
    if [ ! -z "${RESULT}" ]
    then             
        cd "${RESULT}"
    fi
else
    "${TELEPORT_DIR}/tp_cli" "${@}"
fi